Repository kdgs-develop/kdgs-admin-dashboard, pull requests merged in 2025-01, with the labels that each got.

#138 Fix edit cemetery city Closes #137
  app/(dashboard)/edit-obituary-dialog.tsx
  app/(dashboard)/setup/cemetery-administration.tsx
  app/(dashboard)/setup/edit-cemetery-dialog.tsx
Labels: bug

#140 139 admin can edit current open filebox
  app/(dashboard)/create-file-number-dialog.tsx
  app/(dashboard)/edit-obituary-dialog.tsx
  app/(dashboard)/setup/actions.ts
  app/(dashboard)/setup/filebox-administration.tsx
Labels: enhancement

#144 143 add family relationship management
  app/(dashboard)/setup/actions.ts
  app/(dashboard)/setup/add-relationship-dialog.tsx
  app/(dashboard)/setup/edit-relationship-dialog.tsx
  app/(dashboard)/setup/page.tsx
  app/(dashboard)/setup/relationship-administration.tsx
Labels: enhancement

#145 Update actions.ts
  app/(dashboard)/actions.ts
Labels: bug

#146 Update search.tsx
  app/(dashboard)/search.tsx
Labels: enhancement

#147 Update copyright year
  README.md
  app/(dashboard)/obituary/[reference]/page.tsx
  app/api/generate-filebox-report/route.ts
  app/api/generate-pdf/[reference]/route.ts
  app/api/generate-report/route.ts
  app/api/generate-search-pdf/route.ts
  app/layout.tsx
  app/public/obituary/[hash]/page.tsx
  components/footer.tsx
Labels: enhancement

#148 Update edit-obituary-dialog.tsx
  app/(dashboard)/edit-obituary-dialog.tsx
Labels: bug

#149 Save new familyrelationship
  app/(dashboard)/actions.ts
  app/(dashboard)/edit-obituary-dialog.tsx
Labels: bug

#150 Update edit-obituary-dialog.tsx
  app/(dashboard)/edit-obituary-dialog.tsx
Labels: bug

#151 Update create-file-number-dialog.tsx
  app/(dashboard)/create-file-number-dialog.tsx
Labels: bug

#153 Update edit-obituary-dialog.tsx closes #152
  app/(dashboard)/edit-obituary-dialog.tsx
Labels: enhancement

#155 Fix update obit on production closes #154
  app/(dashboard)/actions.ts
  app/(dashboard)/edit-obituary-dialog.tsx
  app/(dashboard)/obituary/[reference]/actions.ts
  lib/db.ts
Labels: bug

#156 Fix location management
  app/(dashboard)/setup/actions.ts
  app/(dashboard)/setup/add-location-dialog.tsx
  app/(dashboard)/setup/location-administration.tsx
  components/ui/combo-form-field.tsx
Labels: bug

#157 Create minio-to-linode-backup.md
  docs/minio-to-linode-backup.md
Labels: documentation

#158 add docs minio backup example
  docs/minio-backup-example/config/settings.json
  docs/minio-backup-example/rclone/rclone.conf
  docs/minio-backup-example/scripts/cleanup-old-backups.ps1
  docs/minio-backup-example/scripts/daily-backup.ps1
Labels: documentation

#160 159 add batch number controlled field
  app/(dashboard)/actions.ts
  app/(dashboard)/add-batch-number-dialog.tsx
  app/(dashboard)/create-file-number-dialog.tsx
  app/(dashboard)/edit-obituary-dialog.tsx
  app/(dashboard)/images/minio-actions.ts
  app/(dashboard)/images/upload-images-dialog.tsx
  app/(dashboard)/obituary/[reference]/page.tsx
  app/(dashboard)/setup/genealogist-administration.tsx
  app/(dashboard)/setup/page.tsx
  app/api/bulk-upload/route.ts
  app/api/generate-pdf/[reference]/route.ts
  app/layout.tsx
  components/footer.tsx
  lib/db.ts
  migrations/migrate-batch-data.ts
  prisma/migrations/20250116083810_migrate_batch_data/migration.sql
  prisma/migrations/20250116084934_remove_old_batch_column/migration.sql
  prisma/schema.prisma
  scripts/update-batch.ts
Labels: enhancement

#164 Update edit-obituary-dialog.tsx
  app/(dashboard)/edit-obituary-dialog.tsx
Labels: enhancement

#167 Update search.tsx
  app/(dashboard)/search.tsx
Labels: enhancement

#168 166 add batch number admin
  app/(dashboard)/add-batch-number-dialog.tsx
  app/(dashboard)/setup/actions.ts
  app/(dashboard)/setup/batch-number-administration.tsx
  app/(dashboard)/setup/edit-batch-number-dialog.tsx
  app/(dashboard)/setup/page.tsx
Labels: enhancement

#171 Update db.ts
  lib/db.ts
Labels: enhancement

#173 Hotfix image list order by
  app/(dashboard)/images/image-table.tsx
  app/(dashboard)/images/minio-actions.ts
Labels: bug

#174 Hotfix handle image table search params
  app/(dashboard)/images/image-table-wrapper.tsx
  app/(dashboard)/images/minio-actions.ts
  app/(dashboard)/images/page.tsx
Labels: bug

#176 175 hotfix save batch number null
  app/(dashboard)/edit-obituary-dialog.tsx
  components/ui/combo-form-field.tsx
Labels: bug

#177 172 add process manager role
  app/(dashboard)/edit-obituary-dialog.tsx
  app/(dashboard)/setup/page.tsx
  prisma/migrations/20250122003313_add_process_manager_role/migration.sql
  prisma/schema.prisma
Labels: enhancement

#179 178 hotfix death date no null
  app/(dashboard)/actions.ts
  app/(dashboard)/edit-obituary-dialog.tsx
Labels: enhancement

#181 Update periodical-administration.tsx
  app/(dashboard)/setup/periodical-administration.tsx
Labels: enhancement

#183 182 add city id relation to periodical
  app/(dashboard)/actions.ts
  app/(dashboard)/edit-obituary-dialog.tsx
  app/(dashboard)/setup/actions.ts
  app/(dashboard)/setup/add-periodical-dialog.tsx
  app/(dashboard)/setup/cemetery-administration.tsx
  app/(dashboard)/setup/edit-periodical-dialog.tsx
  app/(dashboard)/setup/location-administration.tsx
  app/(dashboard)/setup/periodical-administration.tsx
  app/(dashboard)/setup/relationship-administration.tsx
  components/ui/combo-form-field.tsx
  lib/db.ts
  package.json
  prisma/migrations/20250122035923_fix_periodical_cityid/migration.sql
  prisma/schema.prisma
  types/prisma.d.ts
Labels: enhancement

#186 185 add obituary count to batch numbers
  app/(dashboard)/actions.ts
  app/(dashboard)/add-batch-number-dialog.tsx
  app/(dashboard)/edit-obituary-dialog.tsx
  app/(dashboard)/setup/actions.ts
  app/(dashboard)/setup/batch-number-administration.tsx
  app/(dashboard)/setup/edit-batch-number-dialog.tsx
  lib/db.ts
  prisma/migrations/20250122003314_sync_periodical_changes/migration.sql
  prisma/migrations/20250122003315_sync_periodical_changes_again/migration.sql
  prisma/migrations/20250122035923_fix_periodical_cityid/migration.sql
  prisma/migrations/20250123222011_add_batch_number_assigned_obituaries/migration.sql
  prisma/schema.prisma
Labels: enhancement

#187 184 download original image file
  app/(dashboard)/images/edit-image-dialog.tsx
  app/(dashboard)/images/view-image-dialog.tsx
Labels: enhancement
